### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gordonbJumo** [NumbersInternational/flipCluster#1]
Hi guys

After seeing [this](https://www.displayr.com/5-ways-deal-missing-data-cluster-analysis/), I'd like to use this lib on job I'm running. However, I can't get the package installed on R3.4 or R3.3 - "install.packages" returns "package ‘flipCluster’ is not available (for R version 3.3.3)"

Could you give me some pointers? It's difficult to figure out the requirements from the code base for a layman like me.

thanx
gordon

**Comment by TimBock** [comment]
Hi Gordon,

As it is on github, you need to install using:

```
library(devtools)
install_github("Displayr/flipCluster")

```
Tim

**Comment by gordonbJumo** [comment]
Excellent thanx – seems to have worked!

Last question – what format does the dataset need to be in – dataframe / matrix – with text features converted to numerical + frequencies?
And – is there a citation for flipCluster – or do I use Displayr

Cheers
g

**Comment by TimBock** [comment]
Data frame. Other than the blog post, there is no citation.

On 22 Jun 2017, at 8:42 pm, gordonbJumo <notifications@github.com<mailto:notifications@github.com>> wrote:

Excellent thanx – seems to have worked!

Last question – what format does the dataset need to be in – dataframe / matrix – with text features converted to numerical + frequencies?
And – is there a citation for flipCluster – or do I use Displayr

Cheers
g
